version: '2'

services:
  app:
    build:
      context:  .
      dockerfile: ./docker/app/Dockerfile
    image: trophpy:latest
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7

