version: '2'

services:
  app:
    build:
      context:  ./docker/app
      dockerfile: Dockerfile
    image: trophpy/app:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: trophpy/mysql:latest
    volumes:
       - mysqldata:/var/lib/mysqlchrome
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "trophpy"

volumes:
  mysqldata:
    driver: "local"
