version: '2'

services:
  app:
    build:
      context:  ./docker/app
      dockerfile: Dockerfile
    image: trophpy:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    volumes:
       - mysqldata:/var/lib/mysqlchrome
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"

volumes:
  mysqldata:
    driver: "local"
